FROM amazonlinux:2016.09

RUN yum install docker-17.03.2ce-1.59.amzn1 python27 python27-pip -y
RUN pip install awscli

VOLUME "/project"

# entrypoint
ADD base-endpoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint
WORKDIR /project
ENTRYPOINT ["docker-entrypoint"]
